In [1]:
import pandas as pd
import numpy as np

In [2]:
field_types_file = r'../utilfiles/codes_after_reduction.csv'
trn_dataset_with_preprocessing_path = r'../utilfiles/train_test_val_files/train_set_noNulls.csv'
val_dataset_with_preprocessing_path = r'../utilfiles/train_test_val_files/val_set_noNulls.csv'
test_dataset_with_preprocessing_path = r'../utilfiles/train_test_val_files/test_set_noNulls.csv'

In [3]:
field_types_df = pd.read_csv(field_types_file)

# Create a dictionary with field names as keys and field types as values
field_types = dict(zip(field_types_df['codes'], field_types_df['dataType']))

# Separate fields based on their types
categorical_single_fields = [field for field, dtype in field_types.items() if dtype == 'Categorical (single)']
categorical_multiple_fields = [field for field, dtype in field_types.items() if dtype == 'Categorical (multiple)']

categorical_original_fields = categorical_single_fields + categorical_multiple_fields

In [4]:
train_set_df = pd.read_csv(trn_dataset_with_preprocessing_path)

,92-0.0,93-0.0,94-0.0,95-0.0,102-0.0,134-0.0,135-0.0,136-0.0,709-0.0,757-0.0,...,6143-0.0,6144-0.0,6145-0.0,6153-0.0,6154-0.0,6162-0.0,eid,target,31-0.0,34-0.0
0,8.0,139.0,82.0,70.0,81.0,0.0,1.0,1.0,2.0,10.0,...,1,5,4,1,0,2,1000013,1,1,1946.0
1,2007.0,139.0,82.0,70.0,93.0,1.0,0.0,1.0,2.0,25.0,...,1,5,0,0,0,2,1000048,1,0,1939.0
2,2009.0,139.0,82.0,70.0,86.0,0.0,4.0,4.0,1.0,10.0,...,1,5,2,4,5,3,1000055,0,0,1945.0
3,2007.0,139.0,82.0,70.0,65.0,0.0,6.0,2.0,2.0,10.0,...,1,5,0,1,4,3,1000067,0,1,1952.0
4,1987.0,139.0,82.0,70.0,62.0,0.0,2.0,2.0,1.0,10.0,...,1,2,2,1,0,4,1000099,0,1,1944.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344007,1968.0,139.0,82.0,70.0,94.0,0.0,1.0,0.0,2.0,21.0,...,2,5,0,1,5,2,6024021,0,1,1962.0
344008,1968.0,139.0,82.0,70.0,66.0,0.0,4.0,0.0,-1.0,10.0,...,1,5,2,1,4,2,6024039,0,1,1962.0
344009,17.0,139.0,82.0,70.0,77.0,0.0,0.0,2.0,3.0,10.0,...,1,2,0,0,5,3,6024043,0,0,1966.0
344010,1955.0,139.0,82.0,70.0,79.0,0.0,1.0,1.0,3.0,19.0,...,4,5,4,1,3,2,6024085,0,1,1947.0
344011,62.0,139.0,82.0,70.0,66.0,0.0,2.0,1.0,2.0,15.0,...,2,4,0,1,0,2,6024096,0,1,1939.0

In [5]:

train_set_with_dummies = pd.get_dummies(train_set_df, columns=[col for col in categorical_original_fields if col in train_set_df.columns])

,92-0.0,93-0.0,94-0.0,95-0.0,102-0.0,134-0.0,135-0.0,136-0.0,709-0.0,757-0.0,...,6154-0.0_5,6154-0.0_6,6154-0.0_7,6154-0.0_8,6162-0.0_0,6162-0.0_1,6162-0.0_2,6162-0.0_3,6162-0.0_4,6162-0.0_5
0,8.0,139.0,82.0,70.0,81.0,0.0,1.0,1.0,2.0,10.0,...,False,False,False,False,False,False,True,False,False,False
1,2007.0,139.0,82.0,70.0,93.0,1.0,0.0,1.0,2.0,25.0,...,False,False,False,False,False,False,True,False,False,False
2,2009.0,139.0,82.0,70.0,86.0,0.0,4.0,4.0,1.0,10.0,...,True,False,False,False,False,False,False,True,False,False
3,2007.0,139.0,82.0,70.0,65.0,0.0,6.0,2.0,2.0,10.0,...,False,False,False,False,False,False,False,True,False,False
4,1987.0,139.0,82.0,70.0,62.0,0.0,2.0,2.0,1.0,10.0,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344007,1968.0,139.0,82.0,70.0,94.0,0.0,1.0,0.0,2.0,21.0,...,True,False,False,False,False,False,True,False,False,False
344008,1968.0,139.0,82.0,70.0,66.0,0.0,4.0,0.0,-1.0,10.0,...,False,False,False,False,False,False,True,False,False,False
344009,17.0,139.0,82.0,70.0,77.0,0.0,0.0,2.0,3.0,10.0,...,True,False,False,False,False,False,False,True,False,False
344010,1955.0,139.0,82.0,70.0,79.0,0.0,1.0,1.0,3.0,19.0,...,False,False,False,False,False,False,True,False,False,False
344011,62.0,139.0,82.0,70.0,66.0,0.0,2.0,1.0,2.0,15.0,...,False,False,False,False,False,False,True,False,False,False

In [6]:
val_set_df = pd.read_csv(val_dataset_with_preprocessing_path)
test_set_df = pd.read_csv(test_dataset_with_preprocessing_path)

In [7]:
val_set_with_dummies = pd.get_dummies(val_set_df, columns=[col for col in categorical_original_fields if col in train_set_df.columns])
test_set_with_dummies = pd.get_dummies(test_set_df, columns=[col for col in categorical_original_fields if col in train_set_df.columns])

In [10]:
train_set_with_dummies.to_csv('../utilfiles/train_test_val_files/train_set_with_dummies.csv')

In [11]:
val_set_with_dummies.to_csv('../utilfiles/train_test_val_files/val_set_with_dummies.csv')
test_set_with_dummies.to_csv('../utilfiles/train_test_val_files/test_set_with_dummies.csv')